; tpost1.g
; Rev 10 1/26/19 KG
; called after tool 1 has been selected
;
; generated by RepRapFirmware Configuration Tool on Tue Oct 02 2018 10:30:50 GMT-0400 (EDT)
; Wait for set temperatures to be reached
;M116 P1